apiVersion: v1
kind: Config
preference: {}

clusters:
- cluster:
  name: development
- cluster:
  name: scratch

users:
- name: development
- name: experimenter

contexts:
- context:
  name: dev-frontend
- context:
  name: dev-storage
- context:
  name: exp-scratch